# Generated by Django 4.2.6 on 2024-05-06 03:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finalproject', '0003_collectionupvote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorite',
            new_name='Favourite',
        ),
    ]
